# Check out https://docs.codemagic.io/getting-started/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
  ios-app:
    name: iOS App
    environment:
      vars:
        XCODE_WORKSPACE: "project.xcworkspace"
        XCODE_SCHEME: "Runner"
      xcode: latest
      cocoapods: default
    scripts:
      - xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME"
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log